# Game and board constants.
ROWS = 7
COLS = 11
VIEW_SIZE = COLS
VIEW_CENTER = VIEW_SIZE // 2
MAX_STEPS = 200
HUNGER_RATE = 40
SURVIVAL_HORIZON = 2
FALLBACK_SURVIVAL_HORIZON = 1
NUM_PLAYERS = 4
NUM_OPPONENTS = NUM_PLAYERS - 1

# Absolute directions, ordered clockwise.
NORTH, EAST, SOUTH, WEST = range(4)
VALID_DIRECTIONS = (NORTH, EAST, SOUTH, WEST)
DIRECTION_DELTAS = ((-1, 0), (0, 1), (1, 0), (0, -1))
DIRECTION_NAMES = ("NORTH", "EAST", "SOUTH", "WEST")

# Relative policy actions.
FORWARD, LEFT, RIGHT = range(3)
VALID_ACTIONS = (FORWARD, LEFT, RIGHT)
RELATIVE_DIRECTION_OFFSETS = (0, -1, 1)
NUM_ACTIONS = RIGHT + 1
MASKED_LOGIT = float("-inf")

# Observation tensor channels.
OWN_HEAD_CHANNEL = 0
OPPONENT_HEAD_CHANNEL_START = OWN_HEAD_CHANNEL + 1
OWN_TAIL_CHANNEL = OPPONENT_HEAD_CHANNEL_START + NUM_OPPONENTS
OPPONENT_TAIL_CHANNEL_START = OWN_TAIL_CHANNEL + 1
OWN_BODY_CHANNEL = OPPONENT_TAIL_CHANNEL_START + NUM_OPPONENTS
OPPONENT_BODY_CHANNEL_START = OWN_BODY_CHANNEL + 1
FOOD_CHANNEL = OPPONENT_BODY_CHANNEL_START + NUM_OPPONENTS
NUM_CHANNELS = FOOD_CHANNEL + 1
BOARD_TENSOR_SHAPE = (VIEW_SIZE, VIEW_SIZE, NUM_CHANNELS)

# CNN architecture constants.
CONV_CHANNELS = 16
BOARD_FEATURES = 15
TIME_FEATURES = 1
FUSED_FEATURES = BOARD_FEATURES + TIME_FEATURES
VALUE_OUTPUTS = 1
CONV_KERNEL_SIZE = 3
CONV_STRIDE = 1
CONV_PADDING = 0
FLATTENED_FEATURES = CONV_CHANNELS * VIEW_SIZE * VIEW_SIZE

# Periodic-padding source indices for the normalized view.
PERIODIC_PAD_WIDTH = 1
SHORT_AXIS_LOW_PAD_INDEX = VIEW_CENTER + 1
SHORT_AXIS_HIGH_PAD_INDEX = VIEW_CENTER - 1
LONG_AXIS_LOW_PAD_INDEX = VIEW_SIZE - 1
LONG_AXIS_HIGH_PAD_INDEX = 0

# PPO initialization and normalized-time constants.
HIDDEN_INIT_GAIN = 2.0 ** 0.5
ACTOR_OUTPUT_GAIN = 0.01
CRITIC_OUTPUT_GAIN = 1.0
MIN_REMAINING_FRACTION = 0.0
MAX_REMAINING_FRACTION = 1.0
